Token-lose/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'home#index'

  get '/index/:id', to: 'admin#index'

  get '/new', to: 'sessions#new', as: 'users'
  post '/new', to: 'sessions#user_create'

  get '/login', to: 'sessions#admin'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/reset_user', to: 'sessions#reset_user'


  resources 'password_resets'
end

Token-lose/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # before_create :generate_token
  # has_secure_token :reset_digest
  # attr_accessor :remember_token, :activation_token, :reset_token

  def create_reset_digest
   self.reset_token = User.new_token
   update_attribute(:reset_digest,  User.digest(reset_token))
 end

 # Sends password reset email.
 def send_password_reset_email
   generate_token(:reset_digest)
   save!
  #  self.password_resets_sent_at = Time.zone.now
   UserMailer.password_reset(self).deliver_now
 end


  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end


end

Token-lose/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index

  end
end

Token-lose/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: sessions[:user_id])
    end
    @current_user
  end
end

Token-lose/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

Token-lose/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(params[:email])
        if @user
          @user.send_password_reset_email
          flash[:info] = "Email sent with password reset instructions"
          redirect_to "/password_resets/"
        else
          flash.now[:danger] = "Email address not found"
            redirect_to "/"
        end
  end

  def edit
    # @user = User.find_by(id: params[])
  end

  def update
    @user = User.find_by(params[:email])
    @user = User.update(params[:password])
    @user.save
  end
end

Token-lose/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def admin

  end

  def new
    @new = User.new
  end

  def user_create
    if @new = User.new(new_user)
      @new.save
      UserMailer.welcome_mailer(@new).deliver_now
      redirect_to "/login"
    end
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/index/#{user.id}"
    else
      redirect_to "/login"
    end
  end

  def destroy
    session.clear
    redirect_to "/login"
  end

  private
  def new_user
    params.require(:user).permit(:email, :password)
  end
end

Token-lose/app/helpers/admin_helper.rb
module AdminHelper
end

Token-lose/app/helpers/application_helper.rb
module ApplicationHelper
end

Token-lose/app/helpers/home_helper.rb
module HomeHelper
end

Token-lose/app/helpers/sessions_helper.rb
module SessionsHelper
end

Token-lose/app/views/admin/index.html.erb
Your Admin


<br>


<%= link_to "Log out", "/logout", :method => :delete%>

Token-lose/app/views/home/index.html.erb
Hola

<%= link_to "User", "/login"%>

<%= react_component("Post", {title: "Hello World"}) %>

Token-lose/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Venezuelasos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Token-lose/app/views/password_resets/index.html.erb
<div align="center">
<h1>Loses password</h1>

<%= form_for(:password_resets,  url: password_resets_path) do |x| %>

<%= x.label :email, class:"col-sm-2 control-label" %>
<%= x.text_field :email, class:"form-control col-sm-6", placeholder:"Email"%>
<br>
<%= x.submit "Submit", class: "btn-admin btn btn-default col-sm-offset-2 col-sm-6" %>
<% end %>
<%= link_to "back", "/"%>
</div>