Crowdfunding/config/routes.rb
Rails.application.routes.draw do
  resources :users, :projects
  get '/', to: 'index#index'
  get '/save', to: 'users#save'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/explore', to: 'projects#explore'

  get '/home/', to: 'projects#home'
  get '/show', to: 'projects#show'
  # get '/home/:project_id', to: 'projects#explore', as: :explore_path
  get '/home/:project_id/', to: 'projects#explore', as: :project_path
  # get '/home', to: 'projects#payment'
  post '/home/', to: 'projects#payment'
  # post '/home/', to: 'projects#explore'

  get '/config/:project_id', to: 'projects#edit'
  get '/config/', to: 'projects#new'

  get '/post', to: 'posts#new', as: :posts
  post '/post', to: 'posts#create'
  delete '/post/', to: 'posts#destroy'

end

Crowdfunding/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_attached_file :img, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img, content_type: /\Aimage\/.*\z/
end

Crowdfunding/app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  validates_length_of :project_name, :maximum => 20, :allow_blank => true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

Crowdfunding/app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :posts
  has_secure_password
end

Crowdfunding/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    end
    @current_user
  end

  def authorize_user
    unless current_user
      redirect_to "/"
    end
  end
end

Crowdfunding/app/controllers/index_controller.rb
class IndexController < ApplicationController
  before_action :authorize_user, :except => [:index]

  def index
    if current_user.nil?
      @name = "Register/Login"
    else
      @name = current_user.name
    end
    @user = Project.all
  end

end

Crowdfunding/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize_user

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to "/home"
    end
  end

  def destroy
    # binding.pry
    @post = Post.find(params[:post_id])
    @post.destroy
    redirect_to "/home"
  end

  private
   def post_params
    params.require(:post).permit(:post_text, :img)
   end
end

Crowdfunding/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authorize_user, :except => [:explore]

  def new
    if current_user.projects.last
      redirect_to "/config/#{current_user.projects.last.id}"
    else
      @config = Project.new
      # redirect_to "/config/new"
    end
    # @config = Project.new
  end


  def payment
    @deposit = params[:send_java]
    @java = params[:send_java]
    @rails = Project.last.accompanied
    @total_var = Project.last
    @total_var.accompanied = @java.to_i + @rails.to_i
    @total_var.save

    # if @new = Project.last.nil?
    #
    # else
    #   @java = params[:send_java]
    #   @rails = Project.find(params[:project_id]).accompanied
    #   @total_var = Project.find(params[:project_id])
    #   @total_var.accompanied = @java.to_i + @rails.to_i
    #   @total_var.save
    # end
  end


  def explore
    @home = User.find(params[:project_id])
    @text = Project.find(params[:project_id])
    @post = @home.posts

    @java = params[:send_java].to_i

    @rails = Project.find(params[:project_id]).accompanied.to_i
    @total_var = Project.find(params[:project_id])
    @total_var.accompanied = @java + @rails
    @total_var.accompanied.to_s
    @total_var.save
  end

  def edit
    @config = current_user.projects.find(params[:project_id])
  end

  def home
    if current_user.nil?
      @name = "..."
    else
      @name = current_user.name
      @text = current_user.projects
      @post = current_user.posts
    end
  end

  def update
    @config = current_user.projects.find(params[:id])
    if @config.update(user_params)
    end
  end

  def create
    @config = current_user.projects.create(user_params)
    if @config.save
      redirect_to "/home"
    end
  end

  private
  def user_params
    params.require(:project).permit(:avatar, :text, :maximum_amount, :accompanied, :project_name)
  end
end

Crowdfunding/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/home"
    else
      redirect_to "/login"
    end
  end

  def destroy
    session.destroy
    redirect_to "/"
  end
end

Crowdfunding/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_path)

    if @user.save
      redirect_to "/save"
    end
  end

  private
  def user_path
    params.require(:user).permit(:name, :email, :password)
  end
end

Crowdfunding/app/helpers/index_helper.rb
module IndexHelper
end

Crowdfunding/app/helpers/posts_helper.rb
module PostsHelper
end

Crowdfunding/app/helpers/projects_helper.rb
module ProjectsHelper
end

Crowdfunding/app/helpers/users_helper.rb
module UsersHelper
end

Crowdfunding/app/views/index/index.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a href="/login" class="btn btn-outline-success my-2 my-sm-0"><%=@name%></a>

    </form>
  </div>
</nav>


  <div class="banner-div-index">
    <div class="container-fluid">
    <div class="row">
      <div class="text-index-banner text-center">
        <h1 class="col-md-12 size-text">Make it Happen</h1>
        <h3 class="size-text-2">Supports incredible projects to become reality</h3>
        <form action="/users/new">
          <button type="submit" class="start-your-project btn btn-success">Start your Project</button>
        </form>
      </div>
    </div>

    </div>

    <%= image_tag("grafica_web.png", class: "img-responsive img-fluid img-absolut-index") %>
  </div>

  <section class="">
    <div class="container-fluid">
      <div class="row">
        <div class="find-project-index text-center">
          <h3 class="col-md-12 size-find-project">Find a Project and Help finance it</h3>



        </div>
      </div>
    </div>
    <div class="option-project"></div>
  </section>


<section class="result-all-find">
    <% @user.each do |x| %>
    <div class="center-img-index">


    <div class="user-img-index">
      <div class="user-img-circle-index">
    <%= link_to image_tag( x.avatar, class: "avatar-responsive", width: "150", height: "150"),explore_path(x,project_id: x.id) %>
      <% if x.avatar.file? %>
      <!-- <%= image_tag( x.avatar, class: "avatar-responsive img-responsive img-circle", width: "150", height: "150") %> -->
      <% else %>
      <% end  %>
      </div>
        <div class="button-user"> <%= x.project_name %></div>
    </div>
  </div>

    <% end %>

</section>

<footer class="end">



</footer>


<div class="hola">  </div>
<!-- <div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    60%
  </div>
</div> -->

Crowdfunding/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfunding</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Crowdfunding/app/views/posts/new.html.erb
<div class="box-body">
  <div class="type-box2">
    <div class="type-config2">
      <h5 align="center" >New Post</h5>

      <%= form_for @post, html: { multipart: true } do |form| %>
      <div class="avatar-config2">
      <%= form.label :img %> | <%= form.file_field :img %>
      </div>

      <div class="text-config2">
        <div class="text-center">
          <h5><%= form.label :post_text %></h5>
          <%= form.text_area  :post_text, size: "80x10" %>
          <div class="text-center">
            <%= form.submit %>
            <!-- <button type="submit" class="btn-color-config btn btn-primary" name="commit"    value="save">Submit</button> -->
          </div>
        </div>
      </div>
      <% end %>


        <div class="text-center">
          <%= link_to "Back", "/home"%>
        </div>



    </div>

  </div>

Crowdfunding/app/views/projects/_form.html.erb
<div class="box-body">
  <div class="type-box">
    <div class="type-config">
      <h5 align="center" >Config your profile</h5>

      <div class="avatar-config">
      <%= form_for @config, html: { multipart: true } do |form| %>
      <%= form.label :avatar %> | <%= form.file_field :avatar %>
      <button type="submit" class="btn-color-config btn btn-primary" name="commit" value="save">Submit</button>
      <% end %>
      </div>

      <div class="avatar-config">
      <%= form_for @config do |y| %>
      <%= y.label :maximum_amount %> | <%= y.text_field :maximum_amount %>
      <button type="submit" class="btn-color-config btn btn-primary" name="commit" value="save">Submit</button>
      <% end %>
      </div>

      <div class="text-config">
        <%= form_for @config do |x| %>
        <div class="text-center">
        <h5><%= x.label :text %></h5>
        </div>
        <%= x.text_area :text, size: "80x10" %><br>
        <div class="text-center">
        <button type="submit" class="btn-color-config btn btn-primary" align="center" name="commit" value="save">Submit</button>
        </div>
        <% end %>
      </div>

      <div class="text-config">
        <%= form_for @config do |x| %>
        <div class="text-center">
        <h5><%= x.label :project_name %></h5>
        <h5><%= x.text_field :project_name %></h5>
          <div class="text-center">
          <button type="submit" class="btn-color-config btn btn-primary" align="center" name="commit" value="save">Submit</button>
          </div>
        </div>
        <% end %>
      </div>


        <div class="text-center">
          <%= link_to "Back", "/home"%>
        </div>



    </div>

  </div>



  <!-- <%= form_for @config, html: { multipart: true } do |form| %>
  <%= form.label :avatar %>
  <%= form.file_field :avatar %>
  <%= form.submit %>
  <% end %>
<br>
  <%= form_for @config do |x| %>
  <%= x.label :text %>
  <%= x.text_area :text %>
  <%= x.button %>
  <% end %> -->
  <!-- <div class="save-box">
      <div class="flash-message">
        <h4 class="text-center">Your account is already created</h4>
        <h4 class="text-center"><%= link_to "back","/"%></h4>
      </div>
  </div> -->

</div>

Crowdfunding/app/views/projects/avatar.html.erb
<div class="box-config">

  <div class="config-img">
    <h3>Img</h3>


  </div>



    <div class="config-text" data-toggle="modal" data-target="#myModal1">
        <h3>Text</h3>
          <%= form_for @config do |x| %>
          <%= x.label :text %>
          <%= x.text_area :text, :size => 150 %>
          <%= x.button %>
          <% end %>
    </div>

</div>

Crowdfunding/app/views/projects/edit.html.erb
<%= render "form"%>

Crowdfunding/app/views/projects/explore.html.erb
<div class="box-body">
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/explore">Explore <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>


  </div>
</nav>



  <div class="box">

    <div class="user-img">
      <div class="user-img-circle">
        <%if @text.avatar.present?%>
        <%=image_tag(@text.avatar.url, class: "avatar-responsive img-responsive img-circle", width: "150", height: "150")%>
        <% end %>
      </div>

      <div class="button-user"> </div>
    </div>

    <div class="star-project">
      <div class="config-text">

        <%= @text.text%>
      </div>

      <div class="center-post">
          <% @post.each do |x| %>
          <div class="star-project-post">
            <% if x.img.file? %>
          <%= image_tag( x.img, class: "img-responsive img-center", width: "300", height: "300")%>
          <% else %>
          <% end %>
          <%= content_tag(:div, content_tag(:p, x.post_text), class: "p-style-post") %>
          </div>
          <!-- <%= x.post_text%> -->

          <% end %>
      </div>

    </div>

    <div class="form-inline-home">
      <div class="cash">
        <div class="money">
          <h3><%= @text.maximum_amount %> $</h3>
        </div>

        <p class="month-config">Per month</p>
        <button class="follow-btn btn btn-primary" type="button" name="button">Follow</button>
        <h3 class="money-deposit" style="height: 0px;"><%= @text.accompanied %> $</h3>


        <div class="progress">
            <% var = @text.maximum_amount.to_i %>
            <% total = @text.accompanied.to_i * 100 / var %>
          <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= total%>%">
            <%= total = @text.accompanied.to_i * 100 / var %>%
          </div>
        </div>

      </div>
      <div class="form-group">
        <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount">
          <div class="input-group-addon">.00</div>
        </div>
      </div>
       <button class="Transfer-button btn btn-primary">Transfer cash</button>
    </div>




  </div>


</div>

Crowdfunding/app/views/projects/home.html.erb
<div class="box-body">
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Navbar</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/explore">Explore <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>

    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle color-button-home" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        <%=@name%>
        <span class="caret"></span>
      </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <li  align="center"></li>
          <li role="separator" class="divider",></li>
          <li align="center" class="color-li-menu"><%= link_to "Post", "/post", class:"redirect-menu"%></li>
          <li role="separator" class="divider",></li>
          <li align="center" class="color-li-menu"><%= link_to "Config", "/config",class:"redirect-menu"%></li>
          <li role="separator" class="divider",></li>
          <li align="center" class="color-li-menu"><%= link_to "logout", "/logout", class:"redirect-menu", :method => :delete %></li>
          <li role="separator" class="divider",></li>
        </ul>
    </div>
  </div>
</nav>



  <div class="box">

    <div class="user-img">
      <div class="user-img-circle">
        <% @text.each do |x| %>
        <%= image_tag( x.avatar, class: "avatar-responsive img-responsive img-circle", width: "150", height: "150")  %>
      </div>

      <div class="button-user"> <%= x.project_name %></div>
    </div>

    <div class="star-project">
      <div class="config-text">

      <%= x.text %>
      <% end %>
      </div>

      <div class="center-post">
          <% @post.each do |x| %>
          <div class="star-project-post">
            <% if x.img.file? %>
          <%= image_tag( x.img, class: "img-responsive img-center", width: "300", height: "300")%>
          <% else %>
          <% end %>
          <%= content_tag(:div, content_tag(:p, x.post_text), class: "p-style-post") %>
                <%=link_to "", post_path(x, post_id: x.id), class:"fa fa-trash trash-post", align: "right", method: :delete, data: {confirm: "Are your shore??"}%>
          </div>
          <!-- <%= x.post_text%> -->

          <% end %>
      </div>

    </div>

    <div class="form-inline-home">
      <div class="cash">
        <div class="money">
          <% @text.each do |x| %>
          <h3><%= x.maximum_amount %> $</h3>
          <% end %>
        </div>
        <p class="month-config">Per month</p>
        <button class="follow-btn btn btn-primary" type="button" name="button">Follow</button>
        <% @text.each do |x| %>
        <h3 class="money-deposit" style="height: 0px;"> <%= x.accompanied %> $</h3>
        <% end %>

        <div class="progress">
          <% if @text.last  %>
          <% @text.each do |x| %>
            <% var = x.maximum_amount.to_i %>
            <% total = x.accompanied.to_i * 100 / var %>
            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= total%>%">
            <%= total = x.accompanied.to_i * 100 / var %>%
            <% end %>
            <% else  %>
            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
              0%
          <%end%>

          </div>
        </div>
      </div>

      <div class="form-group">
        <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
        <div class="input-group">
          <div class="input-group-addon">$</div>
          <input type="text" class="form-control" id="exampleInputAmount" placeholder="Amount">
          <div class="input-group-addon">.00</div>
        </div>
      </div>
       <button class="Transfer-button btn btn-primary">Transfer cash</button>
    </div>




  </div>
  <!-- <div class="center-post">
      <% @post.each do |x| %>
      <%= content_tag(:div, content_tag(:p, x.post_text), class: "star-project-post") %>
      <% end %>
  </div> -->

<!-- <%= debug(@deposit) %> -->




 <div class="hola" id="pp">  </div>

<!-- # <% @text.each do |x| %>
# <%= x.accompanied %>
# <% end %> -->


</div>




    <!-- <%=@name%> -->
    <!-- <% @text.each do |x| %>
    <%= x.text %>
    <%= image_tag x.avatar %>
    <% end %> -->

Crowdfunding/app/views/projects/new.html.erb
<%= render "form"%>

Crowdfunding/app/views/projects/payment.html.erb
<%=@deposit%>

Crowdfunding/app/views/users/new.html.erb
<div class="login" align="center">
  <form action="/users" class="" method="post">
    <input type="hidden" name="authenticity_token" value="" />

    <label for="">Name</label>
    <input type="text" name="user[name]" value="" placeholder="Name" class="form-control" /><br>

    <label for="">Email</label>
    <input type="text" name="user[email]" value="" placeholder="Email" class="form-control" /><br>

    <label for="">Password</label>
    <input type="password" name="user[password]" value="" placeholder="Password" class="form-control" /> <br>

    <button type="submit" class="btn btn-success btn-block" name="commit" value="save">Submit</button> <br>
    <%= link_to "Back", "/login"%>
  </form>
</div>

Crowdfunding/app/views/users/save.html.erb
<div class="save-box">
    <div class="flash-message">
      <h4 class="text-center">Your account is already created</h4>
      <h4 class="text-center"><%= link_to "back","/"%></h4>
    </div>
</div>